from .books import GET_BOOK_BASIC_BY_BOOK_ID, GET_BOOK_DETAILS_BY_BOOK_ID, GET_BOOK_DETAILS_BY_EDITION_ID, GET_TRENDING_BOOKS
from .editions import GET_THIS_EDITION, GET_BOOK_EDITIONS
from .search import GET_SEARCH_BOOK

__all__ = [
    "GET_BOOK_BASIC_BY_BOOK_ID",
    "GET_BOOK_DETAILS_BY_BOOK_ID",
    "GET_BOOK_DETAILS_BY_EDITION_ID",
    "GET_TRENDING_BOOKS",
    "GET_THIS_EDITION",
    "GET_BOOK_EDITIONS",
    "GET_SEARCH_BOOK",
]
