# Generated by Django 5.2.1 on 2025-05-29 07:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_list', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='book_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
